### PR TITLE
Fix compatibility w/ other terrain generators

### PR DESCRIPTION
**Pull request by T145**
- When other mods take over the world, we shouldn't have a problem with it.

### CODE REVIEW

**Comment by HellFirePvP** [comment]
How would this even happen? A WorldGenerator **has** to have a world being passed in its generate Method. That not happening points to a bigger issue at hand and not something i need to care about.

**Comment by HellFirePvP** [comment]
Looking at the native code, this wouldn't do anything regardless.

**Comment by T145** [comment]
Looking your mod's code or OTG's? OTG uses it's own world objects and such, and I believe one of the problems may be happening w/ how you handle retrogen. You can fix this by simply merging one line of code; or just typing it in yourself. Your world generator will still work just fine; so if you're saying "this wouldn't do anything regardless" in regards to _your_ mod, then you are correct. So it will fix OTG interactions and interactions w/ any other mod that does something just as convoluted.

**Comment by HellFirePvP** [comment]
The world object isn't null on my end. This is a issue with worldgenerator settings where the stronghold isn't yet calculated and thus the world object inside MapGenBase isn't set yet, causing the attempt to potentially calculate said positions where the seed of the Random-generator should be set to the world's one, fails obviously cause the world isn't defined at that point in execution.

So adding a world == null check on my end literally does fck all. As i said, analyse the issue before filing a PR.

**Pull request closed without merging**
