### PR TITLE
Added Minetweaker maven repository

### PR DESCRIPTION
**Pull request by lagonnebula**

### CODE REVIEW

**Comment by p455w0rd** [comment]
ewww...1.10.2? :P

**Comment by HellFirePvP** [comment]
added for both 1.10.2 and 1.11.2

**Comment by lagonnebula** [comment]
Yep sorry :) I made this little change fastly to build the version in 1.10.2 ^^'

**Comment by HellFirePvP** [comment]
I derped again on that though since it now loads CraftTweaker twice into the instance *facepalms* - fixed in dev i'm gonna push that in a few minutes~

**Pull request closed without merging**
