### PR TITLE
Update constellation images and orientations

### PR DESCRIPTION
**Pull request by Swordstone86**
Apparently I can't reopen my PR at #1555, so here's another PR for the extra fixes I finished right before it was merged. Changes are:

- Constellations moved to their own resource location
- Images processed to be more Minecraft-y (check #1555 for images)
- General code robustness improvements

### CODE REVIEW

**Comment by Swordstone86** [comment]
In hindsight, 64x64 leaves a little bit to be desired.

Here are how the background images look at 128x128, with the same process outlined in #1555:

image

I definitely think this looks the best, with a happy medium between the odd smoothness of the originals and the artifacts of the 64x64 pictures.

**Comment by Swordstone86** [comment]
New images are done.

image
image
image
image

PR is ready for merge.

**Comment by HellFirePvP** [comment]
Well you didn't commit the images..?

**Comment by Swordstone86** [comment]
Forgot to push the commits, sorry about that. NOW we're ready to merge.

**Comment by HellFirePvP** [comment]
I've merged them locally, planning to make them available/visible with 1.14.0 :P ^^

**Pull request closed without merging**
