### PR TITLE
Image Optimizations

### PR DESCRIPTION
**Pull request by WesCook**
This PR is to address the large file size of the .jar (currently 39MB).  I've looked into if assets could be optimized, and found many of the images could be substantially compressed with minimal or no quality loss.

First of all, here's an overview of file size distributions (generated using [SpaceSniffer](http://www.uderzo.it/main_products/space_sniffer/)).

distribution

As you can see, most of the size comes from the textures folder.  Many of the large images are 5MB or more, so it adds up to a very large jar.  In addition to the larger download, this will also slow loading times and increase overall memory usage.

I primarily used two optimizations tools to compress.  First I used TinyPNG, which uses a quantization algorithm.  It's technically a lossly process, however the changes are typically very hard to detect and can only be noticed at higher zoom levels (or in a couple edge cases, like gradients).

If you're concerned about quality loss I would suggest comparing any images from before and after.  I think you'll find the shifting is very minimal for the savings gained.  One example:

comparison
(3MB > 780KB)

Results varied largely from this pass, but savings were anywhere from 30-80%.  The largest images were the most affected.

Next I used PngOut, which is truly lossless.  Using this second only results in 1-5% savings typically, but it's completely free so why not.

All in all, this has dropped the /textures folder from 37.1MB to 9.87MB.

### CODE REVIEW

**Comment by HellFirePvP** [comment]
On a side note i want to mention that none of the effect, gui or w/e the biggest textures are ever stitched onto the texture atlas. I previously ran several image compression things, as suggested by others, however those have in most cases resulted into textures that were differently indexed and lwjgl couldn't load them properly anymore, resulting into... well... fully black/white textures or just scrambled things.

I will go over how those textures look ingame as it is not directly visible by viewing them on github or image preview or related.

**Comment by WesCook** [comment]
Great, thanks for taking a look.

I've not experienced the issue you described in my own mods (were I've used these same techniques), so hopefully that doesn't present here either.

**Comment by HellFirePvP** [comment]
It seems to work fine as far as i can tell at the moment. If you don't mind though, i would rather merge this manually since i've had bad experiences with merging images on github...

**Comment by WesCook** [comment]
Sure, however you'd prefer.  If you'd like to skip git entirely I can zip them up as well.

**Comment by HellFirePvP** [comment]
Alright this seems fine, thank you very much, i'll try and keep track of these things myself in the future :P

I merged these images locally and it all seems fine. Due to github image merging issues in the past i'd still refrain from merging this directly here though, so i'll close this PR for now. You should see the images being changed & stuff on the next push though^^

**Pull request closed without merging**
